#!/bin/bash

if [ -z "$1" ]; then
    echo "usage: $0 [vault-path]" 1>&2
    exit 1
fi

wal_template=$HOME/.config/wal/templates/pywal.css

rm_link () {
    rm $1/.obsidian/snippets/pywal.css
}

rm_temp () {
    rm $wal_template
}

echodone () {
    echo "Snippet removed"
}

rm_link $1
rm_temp
echodone
